# -*- coding: utf-8 -*-
"""Monthly Report_streamlit

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MgdHjMz3txogcqA-h8Cy3ec2rShCpk5s
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

st.set_page_config(layout="wide")

st.title("YOY Monthly Report Dashboard")

@st.cache_data
def load_data():
    df24 = pd.read_excel("Processed_Approved_202402.xlsx")
    df25 = pd.read_excel("Processed_Approved_202502.xlsx")

    df24.columns = df24.columns.str.strip().str.lower()
    df25.columns = df25.columns.str.strip().str.lower()
    return df24, df25

df24, df25 = load_data()

def filter_and_classify(df):
    df = df.copy()
    df['account_category'] = df['accounttype'].apply(
        lambda x: 'New account' if str(x).strip().lower() in ['new', 'conversion'] else str(x).strip())
    return df

df24 = filter_and_classify(df24)
df25 = filter_and_classify(df25)

isos = sorted(set(df24['iso'].unique()) | set(df25['iso'].unique()))
selected_iso = st.selectbox("Choose ISO type", isos)

def prepare_pivot(df24, df25, value_col):
    grp_24 = df24.groupby(['iso', 'account_category'])[value_col].sum().unstack(fill_value=0)
    grp_25 = df25.groupby(['iso', 'account_category'])[value_col].sum().unstack(fill_value=0)
    yoy_df = pd.concat([grp_24.add_suffix(' (2024)'), grp_25.add_suffix(' (2025)')], axis=1).fillna(0)
    melted = yoy_df.reset_index().melt(id_vars='iso', var_name='category_year', value_name=value_col)
    melted['category'] = melted['category_year'].str.extract(r'^(.*?) \(')
    melted['year'] = melted['category_year'].str.extract(r'\((\d{4})')
    pivot = melted.pivot(index=['iso', 'category'], columns='year', values=value_col).fillna(0).astype(int).reset_index()
    return pivot

pivot_count = prepare_pivot(df24.assign(dummy=1), df25.assign(dummy=1), 'dummy')
pivot_vol = prepare_pivot(df24, df25, 'monthlyvol')

#def plot_yoy_chart(df, iso, value_label):
    #temp = df[df['iso'] == iso]
    #fig, ax = plt.subplots(figsize=(8, 4))
    #temp.plot(x='category', kind='bar', y=['2024', '2025'], ax=ax)
    #ax.set_title(f"{value_label} - {iso}")
    #ax.set_ylabel(value_label)
    #ax.set_xlabel("Account Type")
    #ax.tick_params(axis='x', rotation=45)
    #st.pyplot(fig)



import plotly.express as px

def plot_yoy_chart(df, iso, value_label):
    temp = df[df['iso'] == iso].copy()
    temp = temp.melt(id_vars='category', value_vars=['2024', '2025'],
                     var_name='Year', value_name=value_label)

    fig = px.bar(
        temp,
        x='category',
        y=value_label,
        color='Year',
        barmode='group',
        title=f"{value_label} - {iso}",
        labels={'category': 'Account Type'}
    )

    fig.update_layout(
        height=400,
        xaxis_tickangle=-15,
        title_font_size=16
    )

    st.plotly_chart(fig, use_container_width=True)


col1, col2 = st.columns(2)

st.subheader("Account Count (YOY)")
plot_yoy_chart(pivot_count, selected_iso, "Number of Accounts")

st.subheader("Volume (YOY)")
plot_yoy_chart(pivot_vol, selected_iso, "Monthly Volume")